apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-na-nuvem-week-frontend-deployment
  labels:
    app: devops-na-nuvem-week-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-na-nuvem-week-frontend
  template:
    metadata:
      labels:
        app: devops-na-nuvem-week-frontend
    spec:
      containers:
      - name: devops-na-nuvem-week-frontend
        image: 968225077300.dkr.ecr.us-west-1.amazonaws.com/devops-na-nuvem-week/production/frontend
        ports:
        - containerPort: 80
