resources:
- deployments/frontend.yml
- deployments/backend.yml
- services/frontend.yml
- services/backend.yml
- ingress.yml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 968225077300.dkr.ecr.us-west-1.amazonaws.com/devops-na-nuvem-week/production/backend
  newName: 968225077300.dkr.ecr.us-west-1.amazonaws.com/devops-na-nuvem-week/production/backend
  newTag: 7c228df34493e4103feb8c7bf52363f05da7a2af
- name: 968225077300.dkr.ecr.us-west-1.amazonaws.com/devops-na-nuvem-week/production/frontend
  newName: 968225077300.dkr.ecr.us-west-1.amazonaws.com/devops-na-nuvem-week/production/frontend
  newTag: 0d1c629f5ebd875be6a28fae7f172991d1a4e49b
