apiVersion: v1
kind: Service
metadata:
  name: devops-na-nuvem-week-backend-service
spec:
  type: NodePort
  selector:
    app: devops-na-nuvem-week-backend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000