apiVersion: v1
kind: Service
metadata:
  name: devops-na-nuvem-week-frontend-service
spec:
  type: NodePort
  selector:
    app: devops-na-nuvem-week-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001